# Generated by Django 6.0.4 on 2026-07-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='contest_id',
            new_name='submitted_contest_id',
        ),
    ]
