# Generated by Django 6.0.4 on 2026-07-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_rename_contest_id_log_submitted_contest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='display_difficulty',
            field=models.FloatField(null=True),
        ),
    ]
