# Generated by Django 6.0.4 on 2026-07-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_problem_display_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='problem',
            name='display_difficulty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
