# Generated by Django 6.0.4 on 2026-07-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_problem_category_alter_problem_display_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_index',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
