# Generated by Django 6.0.4 on 2026-07-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_problem_problem_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_index',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
