# Generated by Django 6.0.4 on 2026-07-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_alter_problem_problem_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='do_later',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='log',
            name='memo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
